<i><b>Public AI</b></i>
<br>
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 1. Numpy Basis**
# Section 1. Numpy의 필요성

**Numpy**는 Python을 대표하는 패키지 중 하나로, 다차원의 데이터를 효율적으로 다루게 해주는 패키지입니다.  Numpy에서의 Array는 수를 다루기 위한 자료구조로, 파이썬에 내장되어 있는 list보다 데이터 처리를 훨씬 빠르고 효율적으로 할 수 있습니다. 이번 시간에는 Numpy를 이용해 효율적으로 데이터를 처리하는 방법을 살펴보겠습니다. 

<img src="https://i.imgur.com/WRK7F2J.png" width="600" height="450"/>

Numpy는 벡터 행렬계산을 효율적으로 처리하기 위한 모듈로 Numeric 모듈과 Numarray 모듈이 합쳐져 높은 수준의 다차원 배열 계산을 고속 및 효율적으로 처리할 수 있습니다. Numpy는 위 그림과 같이 Pandas, Scikit-learn등 데이터 사이언스 분야에서 사용되는 라이브러리들뿐만 아니라 영상처리분야의 OpenCV의 토대가 되는 라이브러리입니다. Numpy는 높은 수준의 기능을 제공하지 않지만 Numpy를 다룰 줄 알아야만 데이터 분석과 영상처리의 이후 단계로 나아갈 수 있습니다.

Numpy의 기능을 본격적으로 살펴보기 전에, 이번 Section1에서는 예제를 통해 Numpy array와 list를 비교해보면서 Numpy가 어떤 경우에 강력한 힘을 발휘하는지 살펴보도록 하겠습니다.

### _Objective_
1. **Numpy 불러오기** : Numpy 패키지를 불러와서 활용하는 방법을 배웁니다. <br>
2. **List와 Numpy Array 비교하기** : List가 아닌 Numpy Array에서 효율적인 인덱싱, 집계연산, 요소별 연산 등이 가능한 사례를 살펴봅니다.

# \[ 1. Numpy 불러오기\]

Numpy를 쓰기 위해서는 Numpy를 호출해야 합니다. `as`를 이용하면 패키지를 별명으로 호출할 수 있는데, Numpy는 주로 np로 줄여서 부릅니다.

In [1]:
import numpy as np

`np.array()`를 이용하면 list 로 만들어진 자료 구조를 Numpy Array로 바꾸어 생성할 수 있습니다. 

In [2]:
np_array = np.array([10, 12])
print(type(np_array))

<class 'numpy.ndarray'>


### 예제 데이터 ) **중간고사, 학생들의 국영수 성적표**

학생들의 성적표를 List와 Numpy로 각각 저장하여 동일한 작업을 할 때 어떻게 다르게 작동하는지 살펴보겠습니다.<br>


| 학생 번호 | 국어 | 영어 | 수학 | 
|  ----   | --- |---| --- |
|0 |80 |92 |70 |
|1 |91 |75 |90|
|2 |86 |76 |42 |
|3 |77 |92 |52 |
|4 |75 |85 |85 | 
|5 |96 |90 |95 |

우선 위의 성적표를 Python이 이해할 수 있는 형식인 list나 Numpy Array로 정리해야 합니다. 6명의 성적표는 학생 별로 성적을 묶어서 아래와 같이 정의할 수 있습니다.

In [3]:
# list로 표현된 학생들의 성적표
scores_list = [
    [80, 92, 70],
    [91, 75, 90],
    [86, 96, 42],
    [77, 92, 52],
    [75, 85, 85],
    [96, 90, 95]
]

# np.array로 표현된 학생들의 성적표
scores_np = np.array([
    [80, 92, 70],
    [91, 75, 90],
    [86, 96, 42],
    [77, 92, 52],
    [75, 85, 85],
    [96, 90, 95]
])

<hr>

# \[ 2. List와 Numpy Array 비교하기\]

그냥 보기에는 Numpy Array는 Python의 list와 매우 유사해 보입니다. 그런데 왜 Numpy Array가 보편적으로 쓰일까요? **인덱스로 원하는 요소 가져오기**, **집계 연산하기**, **요소별 연산하기** 등의 기본적인 기능이 작동하는 방식을 비교해보면서 Numpy의 필요성을 이해해 봅시다. 각각에 대한 자세한 내용은 앞으로의 Numpy 수업 전반에 걸쳐 배울 예정이니 가볍게 이해하고 넘어가시면 됩니다.  

## 1. List와 Numpy의 인덱싱 방법 비교하기
- Python의 List에서와 같이, 인덱싱이란 데이터에서 원하는 값을 가져오는 기능을 뜻합니다. 
- List와 Numpy Array에서 저장된 요소들을 불러오는 '인덱싱' 코드를 비교하여 그 차이를 살펴보겠습니다.

### 예제 (1) 1번째 학생의 성적 가져오기

#### 1) `list`로 가져오기

In [4]:
# fix me!

[91, 75, 90]

#### 2) `np.array`로 가져오기 

In [5]:
scores_np[1]

array([91, 75, 90])

### 예제 (2) 1번부터 3번까지의 학생 성적 가져오기

#### 1) `list`로 가져오기

In [6]:
# fix me!

[[91, 75, 90], [86, 96, 42], [77, 92, 52]]

#### 2) `np.array`로 가져오기 

In [7]:
scores_np[1:4]

array([[91, 75, 90],
       [86, 96, 42],
       [77, 92, 52]])

### 예제 (3) 0번, 4번,5번의 학생 성적 가져오기
여기까지는 Numpy Array와 list의 차이가 거의 보이질 않습니다. 행 단위(이 경우 학생 단위)의 개별 인덱싱이나 범위를 이용한 인덱싱 방법은 거의 유사한 걸 확인했습니다. 이번에는 특정 학생들의 성적을 가져와봅시다. 

#### 1) `list`로 가져오기

In [8]:
# fix me! # 불가능

TypeError: list indices must be integers or slices, not list

위와 같은 방법으로는 불가능하고, 리스트에서 개별 인덱싱을 하여 각 학생의 성적을 가져온 후 이를 list로 합쳐야 합니다. 

In [9]:
# fix me!

[[80, 92, 70], [75, 85, 85], [96, 90, 95]]

#### 2) `np.array`로 가져오기 
한편, Numpy Array에서는 간단하게 **인덱스 리스트를 만들어** 기존의 Numpy Array에서 여러 행(이 경우 0, 4, 5번 학생들)의 성적을 가져올 수 있습니다. 

In [10]:
scores_np[[0,4,5]] # 훨씬 더 간단하게 가져올 수 있음

array([[80, 92, 70],
       [75, 85, 85],
       [96, 90, 95]])

### 예제 (4) 모든 학생들의 국어 성적 가져오기
행 단위의 인덱싱을 살펴보았으니 이번에는 열 단위 인덱싱이 어떻게 되는지 살펴볼까요? 위의 성적 데이터에서 각 열은 과목을 나타냅니다. 국어 과목의 전체 성적을 가져와봅시다. 

#### 1) `list`로 가져오기

list를 사용할 경우, 앞서 `예제1)`에서 각 학생의 성적에 접근했던 방식으로 각 학생의 성적에 접근하여 0번째 과목인 국어의 성적을 가져와야 합니다. 국어 성적을 모아 담을 `language_scores` 라는 빈 list 를 만든 후 `for loop`을 돌며 각 학생의 국어 성적을 추가합니다.  

In [11]:
# fix me!

0 번 학생의 성적 [80, 92, 70] 중 국어 성적은 80 입니다.
1 번 학생의 성적 [91, 75, 90] 중 국어 성적은 91 입니다.
2 번 학생의 성적 [86, 96, 42] 중 국어 성적은 86 입니다.
3 번 학생의 성적 [77, 92, 52] 중 국어 성적은 77 입니다.
4 번 학생의 성적 [75, 85, 85] 중 국어 성적은 75 입니다.
5 번 학생의 성적 [96, 90, 95] 중 국어 성적은 96 입니다.
전체 학생의 국어 성적은? [80, 91, 86, 77, 75, 96]


#### 2) `np.array`로 가져오기 

한편, Numpy 에서는 열에 대해서도 행을 인덱싱 하여 가져왔던 것처럼 바로 접근이 가능합니다. 인덱스 시, `[` 와 `]` 안에 학생을 인덱싱하는 첫번째 자리에는 전체 학생을 의미하는 `:`를 넣고, 과목을 가져오는 두 번째 자리에 국어 과목의 인덱스인 0을 넣습니다. 이렇게 하면 전체 학생의 국어 성적 리스트를 손쉽게 가져올 수 있습니다. 

In [12]:
scores_np[:,0] 

array([80, 91, 86, 77, 75, 96])



## 2. List와 Numpy의 집계연산 비교하기
- 집계연산이란, 여러개의 값을 하나의 값(예: 합, 평균, 요소의 수, 최소값, 최대값 등)으로 결과를 내는 연산을 의미합니다.
- List와 Numpy Array로 구현된 데이터의 집계연산 코드를 비교해 보겠습니다.


### 예제 (5) 중간고사 학생별 전과목 점수 총합

#### 1)  `list`로 가져오기

Python에서는 기본적으로 list를 구성하는 요소의 총합을 구하는 내장함수 `sum`을 제공합니다. 각 학생의 성적을 가져와 각 학생의 성적 총합을 구하여 점수 총합 리스트에 추가해야 합니다. 

In [13]:
# fix me!

[242, 256, 224, 221, 245, 281]

#### 2) `np.array`로 가져오기 
한편, Numpy 에서는 아래와 같이 한 줄 코드로 각 학생의 성적 총합을 구할 수 있습니다. 

In [14]:
scores_np.sum(axis=1) # 한줄로 작성할 수 있다.

array([242, 256, 224, 221, 245, 281])

### 예제 (6) 중간고사 과목별 평균 성적

#### 1)  `list`로 가져오기

In [15]:
# fix me!

[84.16666666666667, 88.33333333333333, 72.33333333333333]

#### 2) `np.array`로 가져오기 


In [16]:
scores_np.mean(axis=0) # 한줄로 작성할 수 있다.

array([84.16666667, 88.33333333, 72.33333333])

## 3. 각 원소 별 연산 적용 비교하기

+ 원소 별 연산이란 List나 Array를 구성하는 각각의 원소 별로 값을 더하거나 빼는 등의 연산을 말합니다. 
+ List와 Numpy Array 각 경우 원소 별 연산을 적용하는 방법을 살펴보겠습니다.


### 예제 (7) 학생들이 만점 대비 각각 몇 점씩 감점 받았는지 표로 만들기

#### 1) `list`로 가져오기
list에서 각 점수를 만점인 100점에서 빼주는 연산을 하려면 `for loop`을 돌면서 리스트의 각 원소를 꺼내 연산을 적용한 후 다시 list에 `append`하는 작업을 반복해야 합니다. 

In [17]:
# fix me!

[[20, 8, 30], [9, 25, 10], [14, 4, 58], [23, 8, 48], [25, 15, 15], [4, 10, 5]]

#### 2) `np.array`로 가져오기 
한편, Numpy Array에서는 아래와 같이 100에서 성적표 Array를 빼주면 모든 원소에 대해 `100-점수`라는 연산이 적용됩니다. 한 줄로 간단하게 원소별 연산을 적용할 수 있게 되는 것이죠.

In [18]:
100 - scores_np

array([[20,  8, 30],
       [ 9, 25, 10],
       [14,  4, 58],
       [23,  8, 48],
       [25, 15, 15],
       [ 4, 10,  5]])

### 예제 (8) 중간고사 대비 기말고사 성적 변동 표 만들기
`예제 (7)`에서 각 원소에 대해 동일하게 100에서 빼는 연산을 적용했다면, 이번에는 각 학생이 과목별로 기말 고사에서 받은 점수가 중간고사 대비 얼마나 성장했는지 계산해보겠습니다. 학생들의 기말고사 성적은 아래와 같습니다. 

In [19]:
# list로 표현된 학생들의 기말고사 성적표
final_scores_list = [
    [85, 95, 72],
    [93, 60, 95],
    [80, 90, 70],
    [80, 94, 56],
    [77, 82, 80],
    [90, 95, 90]
]

# np.array로 표현된 학생들의 기말고사 성적표
final_scores_np = np.array([
    [85, 95, 72],
    [93, 60, 95],
    [80, 90, 70],
    [80, 94, 56],
    [77, 82, 80],
    [90, 95, 90]
])

#### 1) `list`로 가져오기
중간고사 성적(`mid_scores`)과 기말고사 성적(`final_scores`) 두 성적표가 있으니 각 학생의 과목별 중간 고사 및 기말 고사 성적을 묶어 차이를 계산해야 합니다. `zip` 함수를 사용하여 `for loop`를 돌며 각 학생의 과목별 중간/기말 고사 점수를 서로 빼준 후 다시 `diff_scores`라는 결과 리스트에 넣어주어야 합니다. 

In [20]:
# fix me!

[[5, 3, 2], [2, -15, 5], [-6, -6, 28], [3, 2, 4], [2, -3, -5], [-6, 5, -5]]

#### 2)  `np.array`로 가져오기 
한편 Numpy 에서는 두 Array에 대해 `-` 연산을 하면 자동으로 같은 자리의 원소끼리 값을 뺀 결과를 반환합니다. 

In [21]:
final_scores_np - scores_np

array([[  5,   3,   2],
       [  2, -15,   5],
       [ -6,  -6,  28],
       [  3,   2,   4],
       [  2,  -3,  -5],
       [ -6,   5,  -5]])

위에서 살펴본 것처럼 Numpy Array는 list와 유사하게 생겼지만 다양한 연산을 보다 간단한 코드로 적용할 수 있다는 강점을 가지고 있습니다. 코드 작성에 드는 시간과 노력을 아껴줄 뿐만 아니라 실제 연산이 작동하는 시간 역시 훨씬 빠르기 때문에 대용량 데이터 연산일수록 Numpy가 널리 활용되고 있습니다. 그럼 다음 시간부터 본격적으로 Numpy에 대해 알아보겠습니다. 

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/04

---