<i><b>Public AI</b></i>
<br>
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 1. Numpy Basis**
# Section 2. Numpy Array 구성 요소와 생성

Array는 Numpy에서 데이터를 다루는 가장 기본이 되는 자료구조입니다. Numpy에서는 내부적으로 **Array를 중심으로 벡터화하여 연산이 구현(vectorized operation)되어 있기 때문에, 복잡한 Matrix 연산도 간단하고 빠르게 실행할 수 있습니다**. 따라서 Numpy의 강점을 극대화하여 활용하기 위해선 Numpy의 기본 자료 구조인 Array를 이해하는 것이 매우 중요합니다. 

기본적으로 컴퓨터가 데이터를 처리하는 기본 기능에는 'CRUD', 생성(Create), 읽기(Read), 갱신(Update), 삭제(Delete)가 있습니다. 이번 Section 2에서는 Numpy 패키지의 기본 자료구조인 Numpy Array의 구성 요소인 value, shape, data type 등을 이해하고, 이를 기반으로 Numpy Array를 생성(Create)하는 방법을 배워보겠습니다. 

### _Objective_
1. **Numpy Array의 구성 요소**: Numpy Array 생성시 필수 설정 요소인 shape과 data type을 중심으로 numpy array의 기본 구조 및 차원과 축의 개념을 배웁니다. <br>
2. **Numpy Array 생성하기**: Numpy Array를 생성하는 다양한 방법을 배웁니다.  <br>


In [1]:
import numpy as np

# \[ 1. Numpy Array의 구성요소 \]

Numpy Array는 구성 요소(element)의 값(value)과 array의 형태(shape)를 설정해야 생성됩니다. 설정된 값에 따라 데이터 타입(Data type)이 자동으로 부여되기도 하고, 직접 명시할 수도 있습니다. Numpy Array의 중요한 특징인 shape과 datatype에 대해 배워봅시다.

## 1. Data Type

+ Python에서 변수 생성 시, 입력한 데이터의 타입을 파악하여 자동으로 설정됩니다.
+ List에서는 구성 요소의 데이터 타입이 달라도 상관 없습니다. 반면, Numpy의 Numpy Array에서는 **모든 구성 요소의 데이터 타입이 동일해야 합니다.**
+ 때문에 Numpy Array를 생성할 때 입력하는 데이터의 Data Type을 확인( `dtype` 이용)하거나 변환( `astype` 이용)해야 할 때도 있습니다.

### (1) Numpy Array의 자료형변환(`type-casting`)

List는 각 원소의 데이터 타입이 달라도 됩니다. 예를 들어 아래와 같이 정수형, 실수형, 논리형 데이터가 하나의 리스트 안에 들어갈 수도 있습니다. 

In [2]:
# List
# fix me!

[1, 1.2, False]

반면, `np.array`는 `list`와 다르게 행렬 내 모든 타입이 같은 타입이어야만 합니다. 앞서 만든 List와 같이 `[1,1.2,False]`로 Array를 구성하면, Numpy에서는 자동으로 `False`를 `0.`으로 바꾸어 Array를 생성합니다. 이처럼 Numpy에서는 서로 다른 형의 데이터를 입력하여 Array를 구성하면 **데이터의 타입을 통일하기 위해 자동 변환**하여 Array에 담습니다. 

In [3]:
# numpy array
# fix me!

array([1. , 1.2, 0. ])

### (2) `astype`으로 데이터의 타입 임의 변환하기
`astype({변환할 데이터 타입})`으로, np.array를 구성하는 데이터를 원하는 타입으로 바꿀 수 있습니다.

In [4]:
A = np.array([0,1,2,3,4,5])
A

array([0, 1, 2, 3, 4, 5])

In [5]:
# fix me! # int -> float으로 바꾸기

array([0., 1., 2., 3., 4., 5.])

In [6]:
# fix me! # int -> bool으로 바꾸기

array([False,  True,  True,  True,  True,  True])

### (3) `dtype` 으로 `np.array`의 데이터 타입 확인하기
`dtype` 메소드를 이용해 현재 `np.array`를 구성하는 데이터 타입이 무엇인지 알 수 있습니다.

#### 1) boolean array

In [7]:
A = np.array([True,False])
A

array([ True, False])

In [8]:
# fix me!

dtype('bool')

#### 2) int array

In [9]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [10]:
# fix me!

dtype('int64')

#### 3) float array

In [11]:
A = np.array([1.0,2.0,3.0])
A

array([1., 2., 3.])

In [12]:
# fix me!

dtype('float64')

#### ※ numpy의 다양한 데이터 타입들
Numpy에서는 이러한 논리형, 실수형, 정수형 데이터 외에도 다양한 데이터를 다룰 수 있습니다.


|Data Type | Description |
|----|----|
|bool_ | Boolean (True or False) stored as a byte|
|int_ | Default integer type (same as C long; normally either int64 or int32)|
|intc | Identical to C int (normally int32 or int64)|
|intp | Integer used for indexing (same as C ssize_t; normally either int32 or int64)|
|int8 | Byte (-128 to 127)|
|int16 | Integer (-32768 to 32767)|
|int32 | Integer (-2147483648 to 2147483647)|
|int64 | Integer (-9223372036854775808 to 9223372036854775807)|
|uint8 | Unsigned integer (0 to 255)|
|uint16 | Unsigned integer (0 to 65535)|
|uint32 | Unsigned integer (0 to 4294967295)|
|uint64 | Unsigned integer (0 to 18446744073709551615)|
|float_ | Shorthand for float64.|
|float16 | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32 | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64 | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_ | Shorthand for complex128.|
|complex64 | Complex number, represented by two 32-bit floats (real and imaginary components)|
|complex128 | Complex number, represented by two 64-bit floats (real and imaginary components)|

## 2. Shape

+ Numpy에서의 **Shape**은 Array의 '형태'를 뜻합니다. 수학에서의 행렬과 마찬가지로 Numpy Array는 각 축(예: 행과 열)을 구성하는 요소의 수가 같아야 합니다. <br>
+ 메소드 `{array}.shape`로 형태는 어떠한지, `{array}.ndim`으로 몇 차원인지 확인할 수 있으며, `{array}.size`로 몇 개의 원소로 구성되어 있는지 확인할 수 있습니다.<br>
+ Numpy Array에서는 1차원 벡터부터 N차원까지 다차원 행렬까지 모두 구현이 가능하며, `[`과`]`으로 차원을 구분하고 추가합니다. <br>
+ N차원 Numpy Array에서 축은 0번부터 N-1번 까지 번호가 부여됩니다. 축은 집계 연산 혹은 데이터 추가 등 여러 Numpy 함수가 작동하는 기준이 됩니다. 

### (1) Numpy Array의 Shape 조건

Numpy의 Array는 **각 축을 구성하는 요소의 갯수가 같아야 한다**는 점에서 Python의 List와 가장 큰 차이가 있습니다. `list`는 아래와 같이 서로 다른 길이의 리스트를 원소로 담을 수 있습니다.

In [13]:
# list는 아래와 같이 담을 수 있음
A_ = [
    [1,2,3,4,5], # 크기가 5
    [2,3,4,5], # 크기가 4
    [3,4,5,6,7] # 크기가 5
]
A_

[[1, 2, 3, 4, 5], [2, 3, 4, 5], [3, 4, 5, 6, 7]]

반면 `numpy.array`는 아래와 같이 각 행과 열별로 구성하는 원소의 수가 동일하게 정해져 있어야 하며, 이 갯수가 통일되지 않으면 생성할 수 없습니다. `np.array`는 수학에서의 행렬과 같다고 보면 됩니다. 

In [14]:
# array는 행 또는 열별로 크기가 다르면 하나의 array에 담을 수 없음
# fix me!

ValueError: setting an array element with a sequence.

어떻게 고쳐야 할까요? 아래와 같이 각 축(예: 행 또는 열)의 크기가 같아야 np.array를 생성할 수 있습니다.

In [15]:
# array는 행 또는 열별로 크기가 같아야 함
# fix me!

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

위 Array는 3개의 행과 5개의 열로 구성되어 있으며, Numpy Array에서는 이런 행렬의 shape을 아래와 같이 표기합니다.

In [16]:
# fix me!

(3, 5)

shape 표기는 오른쪽에서 왼쪽으로 읽으면 이해하기 쉽습니다. 위 경우 5개의 요소 묶음이 3개 있다는 뜻입니다. 

즉 3 X 5, 15개의 원소로 구성된 array라는 뜻입니다. 이는 `.size`를 이용해 바로 확인할 수 있습니다.  

In [17]:
# fix me!

15

### (2) Numpy Array의 차원(dimension)

Numpy Array에서는 1차원 벡터부터 다차원 행렬까지 모두 구현이 가능하며, `[`과 `]`으로 차원을 구분하고 추가합니다. 예제를 통해 구체적으로 어떻게 작동하는지 살펴봅시다. 

#### 1) 1차원 행렬 `(n,)` 

1차원 행렬은 **Vector(벡터)**라고 부릅니다. 벡터는 `[`와 `]`을 한 단위로 볼 때 한 블럭의 데이터만으로 구성된 Array로 구현됩니다.

In [18]:
A_1D = np.array([1,2,3,4,5])
A_1D

array([1, 2, 3, 4, 5])

In [19]:
# fix me! # 차원 수 

1

1차원 행렬의 경우 `.shape`를 사용하면 하나의 숫자를 반환합니다. 이는 1차원 행렬이라는 의미이며, 이 숫자는 벡터를 구성하는 원소의 갯수를 의미합니다. 

In [20]:
# fix me! # array의 형태

(5,)

In [21]:
# fix me! # array 내부의 원소 수  == 5

5

#### 2) 2차원 행렬 `(n, m)`


2차원 행렬은 수학에서 **Matrix(행렬)**이라고 불립니다. 2차원 행렬은 행과 열로 구성되는데, **`[ 원소 ]` 블럭을 두 레벨로 구성하여 구현**할 수 있습니다. `[`로 블럭을 열고 그 안에 다시 `[`와 `]`로 구성된 벡터를 넣은 후 `]`로 바깥 블럭을 닫으면 두 레벨로 Array가 구성되며 이는 곧 2차원 행렬이 됩니다. 

In [22]:
B_2D = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7]
],dtype=np.int64)
B_2D

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [23]:
# fix me! # 차원 수 

2

Numpy Array에서 Array의 shape의 값은 **가장 바깥에 있는 블럭부터 블럭을 구성하는 요소의 수를 나타낸다** 보면 됩니다. 위의 행렬 `B_2D`를 보면 가장 바깥 블럭은 벡터 3개로 구성되어 있으며, 각각의 벡터는 안에는 5개의 원소가 있습니다. 따라서 `A`의 형태는 (3,5)이며, 이는 행이 3개이고 열이 5개인 Array라는 의미이기도 합니다. 

In [24]:
# fix me! # 행이 3개, 열이 5개

(3, 5)

In [25]:
# fix me! # 내부의 원소 수 : 3(행의 수) * 5(열의 수) == 15

15

조금 더 헷갈릴 수 있는 케이스를 볼까요? 아래의 Array `A_2D`는 앞서 만들었던 1차원 행렬, 벡터 `A_1D`와 동일한 수의 원소로 구성되어 있습니다. 

In [26]:
A_1D

array([1, 2, 3, 4, 5])

In [27]:
A_2D = np.array([[1,2,3, 4, 5]])
A_2D

array([[1, 2, 3, 4, 5]])

In [28]:
print('A_1D의 크기', A_1D.size)
print('A_2D의 크기', A_2D.size)

A_1D의 크기 5
A_2D의 크기 5


이 부분은 Numpy Array에서 1차원 행렬(벡터)인 Array를 만들때 가장 착각하기 쉬운 부분이기도 합니다. Array를 생성하거나 `print`해보면 `[`와 `]` 사이에 가로로 값을 쓰여 있기 때문에 np.arrary로 구현된 벡터가 (1, n) 형태를 가지는 2차원 행렬의 '행'에 해당한다고 착각하기 쉽습니다. 

하지만 A_1D Array를 보면 `[]` 하나를 두고 안에 원소가 들어가있는 반면, `A_2D` Array는 `[[ ]]` 와 같이 대괄호가 2개 입니다. 이는 `(1,5)` 형태를 가지는 2차원 array라는 뜻입니다. 앞서 설명했듯이 **가장 바깥 쪽에 있는 블럭은 1개의 요소로 구성되어 있고, 그 다음 안쪽의 블럭은 5개의 원소로 구성되어 있기 때문에** `(1,5)`의 형태로 표현되는 것이죠. shape을 확인해보면 A_1D는 (n, )의 형태로, 원소 n개로 구성되어 있으며 2차원은 없는 형태임을 기억해야 합니다. 

In [29]:
print('A_1D의 형태', A_1D.shape)
print('A_2D의 형태', A_2D.shape)

A_1D의 형태 (5,)
A_2D의 형태 (1, 5)


In [30]:
print('A_1D의 차원', A_1D.ndim)
print('A_2D의 차원', A_2D.ndim)

A_1D의 차원 1
A_2D의 차원 2


#### ③ 3차원 행렬 `(n, m, d)`

3차원 이상의 행렬은 수학에서 주로 **다차원 행렬(Multidimensional Matrix)라고 부릅니다. `[ ]` 블럭을 세 레벨로 구성하여 구현**할 수 있습니다. 이렇게 크기가 N차원 이상인 모든 행렬들을 통칭해 Tensor라 부릅니다. 이후 배우게 될 `tensorflow` 라이브러리는 tensor, 즉 다차원 행렬을 연산하기 위해 고안된 라이브러리입니다.<br>

In [31]:
A = np.array([
    [
        [1,2,3,4,5],
        [2,3,4,5,6],
        [3,4,5,6,7]
    ],
    [
        [1,2,3,4,5],
        [2,3,4,5,6],
        [3,4,5,6,7]
    ]
])
A

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [32]:
# fix me! # 차원 수 

3

2차원 Array에서 shape은 **가장 바깥에 있는 블럭부터 블럭을 구성하는 요소의 수를 나타낸다**고 했습니다. 위의 3차원 행렬 `A`를 보면 가장 바깥 블럭은 (3,5)의 shape을 가지는 2차원 행렬 2개로 구성되어 있습니다. 따라서 `A`의 형태는 가장 바깥에 있는 블럭부터 요소의 수를 나타낸 `(2, 3, 5)`이 됩니다. 이는 행이 3개이고 열이 5개인 2차원 행렬이 2개있는 3차원 행렬이라는 의미이기도 합니다.

In [33]:
# fix me! # 2x3x5

(2, 3, 5)

In [34]:
# fix me!  # 2x3x5 = 15

30

### (3) Numpy Array의 축(axis)

**데이터가 N차원이라는 것은 N개의 축(axis)이 존재한다**는 의미입니다. Numpy에서는 축을 기준으로 데이터를 다루는 다양한 기능(집계, 데이터 추가 등)을 제공하고 있습니다. 따라서 축의 개념과 집계연산을 할 축을 지정하는 방법을 정확히 이해해야 합니다. 헷갈리기 쉬운 부분이므로 차근 차근 예제를 살펴보며 이해해봅시다.

#### 1) 1차원 벡터의 축
먼저, Numpy에서 축에 이름을 붙이는 방법을 알아봅시다. Numpy에서는 Python의 기본적인 인덱싱 방법을 따라 **축의 이름 역시 0부터 부여합니다**. 

예를 들어, 6개 값으로 구성된 벡터 `A`가 있다고 해봅시다. 벡터 `A`는 1차원 행렬로, 축 또한 1개입니다. shape을 확인하면 `(6,)`라는 결과가 나옵니다. 6개의 값으로 구성된 이 축을 우리는 **0번 축** 이라고 부릅니다.

In [35]:
A = np.array([1,  2,  3,  4,  5,  6])

In [36]:
# fix me! # A의 shape은? 

(6,)

합계를 구할 때 **0번 축을 기준으로 합을 집계한다**는 의미에서 `sum(axis = 0)`으로 설정하면 오류 없이 전체 원소를 더한 값이 계산됩니다. (축을 기준으로하는 다양한 집계함수를 다음 단원에서 배우겠지만, 축의 개념을 이해하기 위해 이번 Section에서는 `sum`을 먼저 사용해보겠습니다.)

![](https://cdn-images-1.medium.com/max/1500/1*MWYX6ziOe9-8r0VbwhLlXw.png)

In [37]:
A.sum(axis=0)

21

축이 0번 축 하나뿐인 벡터를 가지고 **1번 축을 기준으로 합을 집계한다**고 하면 어떻게 될까요? 벡터 `A`에는 1번 축이 없으므로 아래와 같이 오류를 반환합니다. 

In [38]:
A.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

#### ② 2차원 행렬의 축

2차원 행렬에서는 어떨까요? 2차원 행렬 `A`의 shape은 다음과 같이 `(2,3)`입니다. 2개의 축으로 이루어져 있죠.

In [39]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# fix me! # A의 shape은?

(2, 3)

shape의 왼쪽부터 시작해서 순서대로 축의 이름을 붙입니다. `(2, 3)`은 각각 0번 축, 1번 축의 요소 수를 알려줍니다. 즉, 0번 축에는 2개의 요소로 구성되어 있고, 1번 축에는 3개의 요소로 구성되어 있음을 알 수 있습니다. 

![](https://cdn-images-1.medium.com/max/1000/1*DC3vpqXdKZ-ATgqrZiz34w.png)

이번에는 3차원 행렬 `A`를 살펴봅시다. 

In [41]:
A = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
A

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [42]:
# fix me! # A의 shape은?

(2, 2, 3)

`(2, 2, 3)`은 각각 0번 축, 1번 축, 2번 축의 요소 수를 알려줍니다. 즉, 0번 축에는 2개의 요소로 구성되어 있고, 1번 축에는 2개의 요소로 구성되어 있고, 2번 축은 3개 요소로 구성되어 있음을 알 수 있습니다. 

![](https://cdn-images-1.medium.com/max/1000/1*DG93TCxGCbFKfb5JaqyzXA.png)

Numpy에는 축을 기준으로 다양한 작업을 할 수 있습니다. 이에 대해 Section 3에서는 원하는 축을 선택하여 가져오는 인덱싱 방법을 배우고, Section 4에서는 축을 기준으로 데이터를 합치는 방법을 배울 예정입니다.  끝으로 Section 6에서는 축 단위로 데이터에 접근하여 적용할 수 있는 다양한 함수(집계함수, 정렬 함수 등)를 배울 것입니다. 



# \[ 2. Numpy Array 생성하기 \]

Numpy Array를 만드는 방법은 다양합니다. 다른 자료구조로부터 데이터를 받아와 생성할 수도 있고, 하나의 원소로만 구성되는 경우에는 값과 형태와 데이터 타입 등 Array의 구성을 설정하여 생성할 수도 있습니다.   

## 1. 다른 자료로부터 Numpy Array 생성하기

* 이미 생성된 List나 Tuple 또는 다른 Array를 활용하여 새로운 Array를 생성할 수 있습니다.<br>
* List, Tuple로부터 Numpy Array를 생성할 때는 `np.array` 를 사용하고, 다른 Numpy Array로부터 Numpy Array를 복사하여 생성할 때는 `np.copy` 를 활용합니다.


### (1) List 혹은 Tuple로 Array 만들기 : `np.array()`

가장 기본적인 array를 만드는 방식으로, 주로 list나 tuple을 변환하여 array로 만듭니다.

In [43]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [3]:
# fix me!

array([1, 2, 3, 4, 5])

### (2) 기존 Array 복사하기 :  `np.copy()`

똑같은 값을 가진 Array를 만들고자 한다면, `np.copy()`를 이용해야 합니다.

In [44]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

아래와 같은 방법으로 할 경우, A를 복사하는 것이 아닌, 똑같은 A의 값을 가르키고 있는 상태가 됩니다.

In [45]:
# fix me!
print(id(B))
print(id(A))

4658965440
4658965440


`A`와 `B`는 같은 변수를 의미하므로, 하나의 변수 이름(예: B)으로 데이터를 불러 값을 바꾸더라도 다른 변수 이름(예: A)로 불러오는 값도 바뀝니다.

In [46]:
B[0] = 0 # B의 첫번째 원소를 바꾸었을 때, A도 바뀜
B

array([0, 2, 3, 4, 5])

In [47]:
A # B와 같음

array([0, 2, 3, 4, 5])

**값만 가져와 새로운 변수를 생성하고, 기존 변수에는 영향을 미치고 싶지 않다**면 어떻게 해야 할까요? 위와 같은 상황을 방지하기 위해서는 `copy`라는 메소드를 이용해야 합니다.

In [48]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [49]:
# fix me! # 이렇게 할 경우, A를 복사하여 저장
print(id(B))
print(id(A)) # 서로 다른 메모리 위치에 저장

4658992272
4658991632


In [50]:
B[0] = 0 # B의 첫번째 원소를 바꾸었을 때, A는 바뀌지 않음
B

array([0, 2, 3, 4, 5])

In [51]:
A # B와 다름

array([1, 2, 3, 4, 5])

<br>

## 2. 구성을 설정하여 Numpy Array 생성하기

+ 앞서 Numpy Array는 값(Value), 형태(Shape), 데이터 타입(Data type)로 구성된다고 배웠습니다. 이런 구성(Value, Shape, Datatype)을 각각 설정하여 Numpy Array를 생성할수도 있습니다.<br>
+ Array의 구성 요소가 동일한 값을 가지도록 하여 생성할 수도 있습니다.(예:  np.zeros() ,  np.ones() ,  np.full() 활용)
+ 기존 Numpy Array의 Shape만 가져와 다른 값을 가지도록 생성할 수도 있습니다.(예: np.zeros_like() ,  np.ones_like() ,  np.full_like() 활용)
+ 요소들의 값들을 등간격으로 설정하여 생성할 수도 있습니다.(예: np.linspace()  ,   np.arange() 활용)


### (1) 값이 일정한 Array 생성하기: `np.zeros()`&nbsp;,&nbsp; `np.ones()`&nbsp;,&nbsp; `np.full()`

Array를 생성할 때, 지정할 수 있는 파라미터에는 크게 `shape`, `value`, `dtype` 등이 있습니다. Array를 동일한 값으로 구성하려 한다면,  `value`는 정해졌으므로 `shape`와 `dtype`를 정해 설정합니다. 

In [52]:
# 값은 0이고, 3행 2열로 구성된 행렬
# fix me!

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
# 값은 1이고, 3행 2열로 구성된 행렬
# fix me!

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
# 값은 3이고, 3행 2열로 구성된 행렬
# fix me!

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

### (2) 기존 Array와 동일한 shape의 Array 생성하기 : `np.zeros_like()`&nbsp;, &nbsp;`np.ones_like()`&nbsp;, &nbsp;`np.full_like()`&nbsp;
기존의 Numpy Array의 형태(shape)가 동일하되, 원하는 값으로 채워진 Numpy Array를 생성할 수 있습니다.

In [55]:
# Shape를 본 딸 Numpy Array : A 생성
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [56]:
# fix me! # A와 같은 Shape이면서 모든 요소의 값이 0 인 Numpy Array 생성

array([0, 0, 0, 0, 0])

In [57]:
# fix me! # A와 같은 Shape이면서 모든 요소의 값이 1 인 Numpy Array 생성 

array([1, 1, 1, 1, 1])

In [58]:
# fix me! # 3. A와 같은 Shape이면서 모든 요소의 값이 13 인 Numpy Array 생성

array([13, 13, 13, 13, 13])

### (3) 같은 간격의 값으로 구성된 Array 생성하기 :  `np.linspace()`&nbsp; , &nbsp; `np.arange()`

등간격으로 배치된 Array를 만들고 싶을 때도 Numpy에서는 메소드를 통해 간단히 만들 수 있습니다. 예를 들어 1부터 10까지 일정 간격으로 커지는 연속적인 값으로 구성된 Array를 구성한다면 다음 두 가지 방법을 활용할 수 있습니다.

* `np.linspace` : 1부터 10 사이를 **<몇 개의 숫자로 구성할까?>를 기준**으로 Array를 만듭니다.
* `np.arange` : 1부터 10 사이를 **<얼만큼의 간격으로 나눌까?>를 기준**으로 Array를 만듭니다.

In [59]:
# fix me! # 1. 1부터 10까지 19개의 요소를 등간격으로 쪼개서 생성

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [60]:
# fix me! # 2. 1부터 10까지 0.5 step(간격)으로 더하여 요소를 생성

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/08/25


---