<i><b>Public AI</b></i>
<br>
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 1. Numpy Basis**
# Section 3. Numpy Array 의 인덱싱

이제 Array를 생성하는 방법을 배웠으니 원하는 값을 가져오는 방법을 배울 차례입니다. 앞서 Section 2에서 2차원 행렬에서 `A[0,0]`과 같은 식으로 원하는 행렬에서 원하는 값을 가져왔었습니다. Section 2에서는 작동 방식에 대한 구체적인 설명 없이 지나갔었죠. 

이번 Section 3에서는 Numpy Array에서 원하는 값을 가져오는 인덱싱 기능의 그 구체적인 작동방식과 다양한 인덱싱 방식을 배워보겠습니다. 인덱싱 방법을 이해하면 컴퓨터가 데이터를 처리하는 기본 기능인 CRUD, 생성(Create), 읽기(Read), 갱신(Update), 삭제(Delete) 중 읽기, 갱신, 삭제 등을 자유롭게 할 수 있습니다. 

### _Objective_
1. **원하는 위치의 원소 또는 축 가져오기** : Numpy Array에서 원하는 위치의 값을 가져오는 방법을 배웁니다.
2. **조건에 맞는 값 가져오기** : Numpy Array에서 조건식을 이용하여 조건에 맞는 값을 가져오는 방법을 배웁니다. 

In [1]:
import numpy as np

# \[ 1. 원하는 위치의 원소 또는 축 가져오기 \]
 
Python의 `string`, `list` 등의 값을 가져올 때 썼던 인덱싱(indexing) 방법과 유사한 방법으로 `np.array`에서 원하는 값을 가져올 수 있습니다. Numpy Array도 `string`, `list` 등과 마찬가지로 **구성하는 요소에 순서**가 있기 때문입니다. 아래 데이터를 예제로 이용하여 Numpy Array에서 원하는 위치에 있는 값을 가져오는 방법을 배워봅시다.

#### ** 예제 데이터 ) 학생들의 국영수사과 성적표**

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |



In [32]:
scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])
scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

## 1. 특정 위치의 단일 원소 가져오기

+ Numpy Array를 인덱싱 할 때에도 list나 string 인덱싱에서 사용했던 대괄호 형식 `[인덱스 값]`을 사용합니다. 
+ N차원 행렬의 경우 각각의 축에 대해 위치를 특정하면, 원하는 위치의 원소를 가져올 수 있습니다.

### (1) 원소 1개 가져오기 
2차원 행렬에는 축이 2개 있으므로 단일 원소를 가져오려면 각 축에 대한 인덱스 값이 필요하며, 이는 `[a, b]`로 표현할 수 있습니다. 첫번째 값 `a`는 "0번 축에서 가져올 요소의 인덱스 값"이며 두번째 값 `b`는 "1번 축에서 가져올 요소의 인덱스 값"을 의미합니다. 2차원 행렬에서는 axis = 0이 행, axis = 1이 열을 뜻하므로, `[행의 인덱스, 열의 인덱스]`라고 생각하면 됩니다. 각 축에서 가져오고자 하는 값의 인덱스를 을 특정하면 해당하는 값에 바로 접근할 수 있습니다. 

#### 1) 학생 번호 2번의 국어 성적을 가져오기

In [3]:
# fix me! # 국어의 열 index = 0

86

#### 2) 학생 번호 3번의 수학 성적을 가져오기

In [4]:
# fix me! # 수학의 열 index = 2

52

## 2. 축을 기준으로 원하는 값 가져오기
 
+ Numpy Array에서는 원하는 축을 기준으로 값을 선택하여 한 번에 가져올 수 있습니다.
+ `[ ]` 안에 인덱스 값은 0번 축부터 순서대로 인덱싱하는 방식이며, 해당 축의 값을 전부 가져온다면 `:`를 사용할 수 있습니다.
+ 0번 축부터 순차적으로 인덱싱을 시작해나가다가 더 이상 인덱싱 값을 특정 하지 않으면 그 이상의 축에 대해서는 값을 전부 가져오는 것으로 이해하고 작동합니다. 
+ 2차원 행렬에서는 원하는 행 또는 1번 축(열)을 특정하여 원하는 축에 있는 원소를 전부 가져올 수 있습니다.

### (1) 특정 행 전체 가져오기 

Numpy에서 인덱스는 축 순서대로 입력해야 합니다. n차원의 Array라면 0번 축부터 순서대로 인덱스 값을 입력하면 됩니다. 가령 2차원 행렬에서는 0번 축(행)에서 하나를 선택하고 1번 축(열)은 전부 가져오려면 `[0번 축에서 선택한 요소의 인덱스, :]`로 설정합니다. 여기서 `:` 는 파이썬의 리스트에서와 같이 "전부"를 의미합니다. 열을 `:`로 표시하지 않고 비워 두면 자동으로 전체 열을 가져옵니다. `:`은 전체를 의미하므로, 선택한 행에 해당하는 데이터를 전부 가져오게 됩니다. 


#### 1) 학생 번호 1번의 전체 성적 가져오기

In [5]:
# fix me! # 0번 축(학생)은 1번, 1번 축(과목)은 전체 

array([91, 75, 90, 68, 85])

0번 축부터 값을 특정하여 인덱싱 하다가 더 이상 인덱싱 값을 특정하지 않으면 **"자동으로 나머지 축은 전부 가져온다"로 설정**됩니다. 위 예제에서 가져왔던 1번 학생의 성적은 다음과 같이 `scores[1]`로 하여도 가져올 수 있습니다.

In [6]:
# fix me! # 0번 축에서 1번 요소(1번 학생)의 전체 성적 데이터

array([91, 75, 90, 68, 85])

### (2) 특정 열 가져오기 

열만 특정하고 행의 인덱스를 제시해야 할 자리에 `:`를 설정하게 되면, 열에 해당하는 데이터를 전부 가져오게 됩니다. 여기서도 `:` 는 "전부"를 의미합니다.

#### 1) 전체 국어 성적 가져오기

In [7]:
# fix me! # 전체 국어 성적

array([80, 91, 86, 77, 75, 96])

하지만 1번 이상의 축(1번 축, 2번 축, 3번 축 등)은 `:`로 표시하지 않고 비워 둘 수는 없습니다. 앞서 0번 축만은 단독으로 인덱싱이 가능하다고 하였는데, 여기서 특정하여 가져오려고 하는 축은 0번 축이 아닌 1번 축이기 때문에 "나머지 축은 전부 가져온다"는 설정이 자동으로 작동하지 않습니다. 반드시 위와 같이 해당 축의 인덱스를 입력하는 자리에 축에서 원하는 요소를 특정하거나 혹은 `:` 표시를 해야 합니다.

In [8]:
# fix me! # 0번째 축인 행 기준 0번 요소 (= 학생번호 0번)의 성적을 반환함

array([80, 92, 70, 65, 92])

## 3. 특정 범위만 가져오기

+ Numpy Array에서는 하나의 요소만 선택할 수 있는건 아닙니다. 특정 부분을 **범위로 지정해서 가져올 수 있습니다**.
+ 범위는 list나 string을 인덱싱할 때 사용했던 `:`로 설정할 수도 있고(slice 방식), 가져오고자 하는 범위의 인덱스 값을 list로 만들어 설정할 수도 있습니다(list 방식). 

### (1) slice 방식으로 가져오기

인덱스를 입력하는 자리에 `[시작:끝]` 식으로 인덱스를 입력하면 시작 인덱스는 포함하고 끝 인덱스는 포함하지 않는 범위로 데이터를 가져올 수 있습니다. 
학생은 0번 축이므로 1번 축을 따로 특정하지 않으면 자동으로 '전부' 가져오게 됩니다.

#### 1) 학생 번호 1번부터 n번까지의 전 과목 성적 가져오기

In [9]:
# fix me! # 1<=학생번호<5 까지의 값을 가져올 수 있음. 즉, [시작:끝]에서 끝에 해당하는 값은 가져오지 않음.

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95]])

In [10]:
# fix me! # 끝까지 지칭하는 경우, 끝값(6)은 생략 가능

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

#### 2)  홀수 번째 학생의 전 과목 성적 가져오기

In [11]:
# fix me! # scores[1:6] 에서 인덱스값 2씩 증가하며 가져오기. 즉 [[1, 1+2, 1+2+2]]에 해당하는 값

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [96, 90, 95, 81, 72]])

In [12]:
# fix me!

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [96, 90, 95, 81, 72]])

#### 3) 전체 학생의 국영수 성적만 가져오기

열도 마찬가지로 `[시작:끝]`을 이용하면 범위로 데이터를 가져올 수 있습니다. 역시나 1번 축인 과목을 특정하고, 0번 축인 학생은 전부 가져오고 싶다면 반드시`:` 표시를 해주어야 합니다. 

In [13]:
# fix me! # 열 방향도 동일한 방식으로 지정할 수 있음

array([[80, 92, 70],
       [91, 75, 90],
       [86, 76, 42],
       [77, 92, 52],
       [75, 85, 85],
       [96, 90, 95]])

In [14]:
# fix me! # 시작이 0인 경우 생략 가능

array([[80, 92, 70],
       [91, 75, 90],
       [86, 76, 42],
       [77, 92, 52],
       [75, 85, 85],
       [96, 90, 95]])

### (2) list 방식으로 가져오기

#### 1) 학생 번호 1번, 3번, 4번의  전 과목 성적 가져오기

In [15]:
# fix me! # 직접 학생 번호들을 list에 담아서 지칭할 수 있음

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95]])

#### 2) 수학과 과학의 전 과목 성적 가져오기

In [16]:
# fix me!

array([[70, 92],
       [90, 85],
       [42, 88],
       [52, 80],
       [85, 95],
       [95, 72]])

In [17]:
# fix me! # 꼭 오름차순으로 가져올 필요 없이, 순서를 바꿀 수 있음

array([[92, 70],
       [85, 90],
       [88, 42],
       [80, 52],
       [95, 85],
       [72, 95]])

# \[ 2. 조건에 맞는 값 가져오기 \]

Numpy Array 에서는 가져오고자 하는 값을 True와 False로 구성된 Boolean Mask를 만들거나 `where` 메소드를 이용하여 원하는 값만 가져올 수 있습니다. Boolean Mask는 직접 True와 False로 구성된 리스트를 만들거나 비교 연산자(`<`, `>`, `=`)를 이용하여 만들 수 있습니다. 한편 `.where()` 메소드의 파라미터로 비교 연산자를 이용한 조건문을 활용하여 해당하는 값의 Index Array를 만들어 원하는 값만 가져올 수 있습니다. 각 방법을 구체적으로 살펴봅시다. 

<div class="alert alert-success" role="alert">
    컴퓨터 과학에서 불리언(boolean) 자료형은 논리 자료형이라고도 하며, 참과 거짓을 나타내는 데 쓰인다. 주로 참은 1, 거짓은 0에 대응한다. <br> 불리언(Boolean)이라는 말은 영국의 수학자 겸 논리학자인 조지 불(George Boole)의 이름에서 따온 것이다.
</div>

## 1. 직접 Boolean Mask 만들어 가져오기
+ Boolean Mask는 True / False 값으로 구성된 Array를 뜻하며, Numpy Array에서 원하는 값을 가져올 때 인덱스로 활용할 수 있습니다.
+ Boolean Mask 또는 Index Array를 `[`와`]`에 넣으면 해당 조건에 맞는 값만 가져올 수 있습니다.
+ Boolean Mask는 인덱스하고자 하는 Array와 차원이 같을 필요는 없지만, 0번 축이 동일한 요소 수를 가지도록 만들어야 합니다. 


### (1) 2차원 행렬을 Boolean Mask로 인덱싱하기
2차원 행렬의 Boolean Mask는 1차원 벡터로 만들 수도 있고, 2차원 행렬로 만들 수도 있습니다. Boolean Mask를 이용하려면 **인덱스 하려는 Array와 Boolean Mask에서 0번 축의 요소 수가 같아야 한다**는 조건만 충족하면 됩니다.

예를 들어, 아래와 같이 `(2,3)`의 shape을 가지는 Numpy Array를 인덱스한다고 생각해봅시다. 

In [18]:
x = np.arange(0,6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
x[np.array([True,False])]

array([[0, 1, 2]])

#### 1) 1차원 벡터 형태인 Boolean Mask

Boolean Mask를 이용하려면 인덱스 하려는 Array와 Boolean Mask에서 0번 축의 요소 수가 같아야 한다고 했습니다. 위 Array의 경우, 0번 축은 2개의 요소로 구성되어 있습니다. 따라서 Boolean Mask 역시 0번째 축은 반드시 2개의 요소로 구성되어야 합니다. 0번 축의 요소가 2개인 1차원 형태의 Boolean Mask를 만들어봅시다. 

In [20]:
bool_mask_1D = np.array([True, False])

In [21]:
x[bool_mask_1D].shape

(1, 3)

앞서 생성한 `x`는 2차원 행렬이어서 괄호가 두 레벨로 구성되어 있습니다. 한편 `bool_mask_1D`는 한 레벨로 구성되어 있어 1차원 벡터라는 것을 알 수 있습니다. 

In [22]:
print('x는 몇 차원? ', x.ndim) 
print('bool_mask_1D는 몇 차원? ', bool_mask_1D.ndim)

x는 몇 차원?  2
bool_mask_1D는 몇 차원?  1


In [23]:
print('x의 shape은?', x.shape) # 0번째 축이 2개로 구성
print('bool_mask_1D의 shape은?', bool_mask_1D.shape) # 0번째 축이 2개로 구성

x의 shape은? (2, 3)
bool_mask_1D의 shape은? (2,)


이처럼 인덱스하고자 하는 Array와 Boolean Mask의 차원 수가 동일할 필요는 없지만 0번 축의 요소 수는 동일해야 합니다. **`bool_mask_1D`에서 `[True, False]`는 x의 0번째 축의 0번 요소는 가져오고(True) 1번 요소는 가져오지 않는다(False)는 뜻**입니다. Boolean Mask를 이용해 인덱싱 한 결과를 살펴봅시다. 

만일 Boolean Mask를 원소 1개로 구성된 `(1,)` 형태로 만든다면 어떻게 될까요? 아래와 같이 **0번째 축의 요소 수가 2개여야 하는데 1개여서 오류를 반환합니다.**

In [24]:
bool_mask = np.array([True])
bool_mask.shape

(1,)

In [25]:
x[bool_mask]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1

#### 2) 2차원 행렬 형태인 Boolean Mask

그럼 0번 축과 함께 1번 축에 대해서도 `True`와 `False` 값으로 인덱싱을 하고 싶다면 어떻게 해야 할까요? 2차원으로 Boolean Mask를 만들어야 합니다. **0번째 축을 구성하는 요소의 수가 동일해야 한다**는 최소한의 조건을 충족한 상태에서 하나의 조건이 더 추가됩니다. 인덱스 하고자 하는 Array의 N번째 차원에 대해서도 조건을 걸어 값을 가져오고 싶다면, **1번 축 이상의 축에 대해서는 인덱스하고자 하는 Array와 동일한 요소 수를 가지도록 Boolean Mask**를 만들어야 합니다. 

In [26]:
bool_mask = np.array([
    [True,False, True],
    [False,False, True]])
bool_mask.shape # 인덱스 하고자 하는 Array의 shape = (2,3)

(2, 3)

In [27]:
x[bool_mask]

array([0, 2, 5])

N번째 차원의 값이 다르면 아래와 같이 오류를 반환하게 됩니다. 

In [28]:
bool_mask = np.array([
    [True],
    [False]])
bool_mask.shape # 인덱스 하고자 하는 Array의 shape = (2,3)

(2, 1)

In [29]:
x[bool_mask]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 1

### (2) 3차원 행렬을 Boolean Mask로 인덱싱하기
3차원 Array를 Boolean Mask로 인덱싱 할 때는 어떻게 해야 할까요? 이때는 1차원 벡터, 2차원 행렬, 3차원 행렬 형태로 Boolean Mask를 만들 수 있습니다. 먼저 3차원 행렬을 만들어봅시다.

In [30]:
x = np.arange(0,27,1).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 1) 1차원 벡터 형태인 Boolean Mask

앞서 살펴본 2차원 행렬의 예시와 마찬가지로 1차원 벡터 형태의 Boolean Mask는 0번 축의 요소를 가져올지 여부를 반영할 수 있다고 생각하면 됩니다. 아래와 같이 `[True,False,False]`가 있다면, 0번 축에서 0번 요소는 가져오고, 1번 요소와 2번 요소는 가져오지 않는다는 뜻의 인덱싱입니다. 

In [31]:
mask = np.array([True,False,False])
mask

array([ True, False, False])

In [32]:
x[mask] # 0번 축의 0번 요소만 가져옴

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### 2) 2차원 행렬 형태인 Boolean Mask

shape이 `(3, 3, 3)`인 3차원 행렬 `x`를 2차원 행렬 형태의 Boolean Mask로 인덱싱 하려면 반드시 `(3, 3)` 형태여야 합니다. **0번 축을 구성하는 요소의 수가 동일해야 하고 1번 축 이상의 축에 대해서는 인덱스하고자 하는 Array와 동일한 요소 수를 가지도록 Boolean Mask**를 만들어야 하기 때문입니다. `(3,3)` 형태의 Boolean Mask를 만들어봅시다.

In [33]:
mask = np.array(
    [[True,True,False],
     [True,False,True],
     [True,False,False]])
mask

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False, False]])

In [34]:
mask.shape

(3, 3)

위와 같은 형태의 `mask`로 인덱싱하면 어떤 결과를 반환할까요? 

먼저 `mask`의 0번 축의 0번 요소를 보며 어떤 의미인지 생각해봅시다.

In [35]:
mask[0, :]

array([ True,  True, False])

`x`의 0번 축 0번 요소는 아래와 같이 생겼습니다. 

In [36]:
x[0, :, :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

`mask[0, :]`가 `array([ True,  True, False])`와 같다는 뜻은 `x`의 0번 축 0번 요소 안에서 1번 축의 0번 요소와 1번 요소를 가져오고(True) 2번 요소는 가져오지 않는다(False)는 뜻입니다. 

In [37]:
x[0, [0,1], :]

array([[0, 1, 2],
       [3, 4, 5]])

다시 앞서 만들었던 `(3,3)` 형태의 mask를 살펴봅시다. 어떤 결과가 나올지 예상해보면 다음과 같을 것입니다. 

In [38]:
mask

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False, False]])

0번 축의 0번 요소 중 
- 1번 축의 0번 요소**(True)**
- 1번 축의 1번 요소**(True)**
- 1번 축의 2번 요소(False)
<br>
<br>

0번 축의 1번 요소 중 
- 1번 축의 0번 요소**(True)**
- 1번 축의 1번 요소(False)
- 1번 축의 2번 요소**(True)**
<br>
<br>

0번 축의 2번 요소 중 
- 1번 축의 0번 요소**(True)**
- 1번 축의 1번 요소(False)
- 1번 축의 2번 요소(False)

`mask`를 `x` 의 인덱스로 사용하게 되면, `x`중 위에서 True에 해당하는 값만 반환합니다. 

In [39]:
x[mask] 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [18, 19, 20]])

## 2. 비교 연산자로 Boolean Mask 만들어 가져오기

+ 비교 연산자를 이용하여 Boolean Mask를 생성할 수도 있습니다. 
+ 비교문은 단독으로 구성할 수도 있고 여러 비교문을 `and`나 `or`로 합쳐서 복합적인 비교문을 만들 수도 있습니다. 

### (1) 단독 비교문으로 Booelan Mask 만들기
앞서 살펴본 것처럼 True, False로 구성된 Boolean Mask를 직접 만들 수도 있지만, 생성해둔 np.array에 대해 비교 연산자를 지정하면 각 원소 별로 조건문 결과가 True, False 인지 반환합니다. 즉, 자동으로 Boolean Mask가 생성되는 것이죠. 마찬가지로 비교문을 인덱스값으로 `[`와`]`에 넣으면 True에 해당하는 값만 반환합니다. 

In [40]:
language_score = scores[:,0]
language_score

array([80, 91, 86, 77, 75, 96])

In [41]:
# fix me! # 각 원소별로 80보다 큰지 비교

array([False,  True,  True, False, False,  True])

In [42]:
scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

In [43]:
# fix me! # 국어 점수가 80점 이상인 학생들의 성적을 가져오기

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [96, 90, 95, 81, 72]])

In [44]:
# fix me! # 각 원소별로 95보다 작은지 비교

array([ True,  True,  True,  True,  True, False])

### (2) 2개 이상의 비교문으로 Booelan Mask 만들기
조건문이 2개 이상이 필요한 경우, `(조건문1) & (조건문2)` 또는 `(조건문1) | (조건문2)`으로 표현하여 두 개 이상의 조건문을 결합한 결과를 `True`와 `False`로 반환받을 수 있습니다.

In [45]:
# 두 조건문을 둘다 만족하는 경우는 & 연산자로 표현
# fix me! # 국어점수가 80점 이상, 95점 이하인 학생들에 대한 Boolean Mask

[False  True  True False False False]
[91 86]


In [46]:
# 두 조건문 중 하나라도 만족하는 경우는 | 연산자로 표현
# fix me! # 국어점수가 80점 이상이거나 95점 이하인 학생들에 대한 Boolean Mask

array([ True,  True,  True,  True,  True,  True])

이러한 논리형 데이터로 구성된 Array를 인덱스로 직접 사용하여 `[ ]`에 넣게 되면, `True`에 해당하는 값만 반환받게 됩니다.

In [47]:
# fix me! # 국어 점수가 80점 이상인 학생들의 국어점수

[False  True  True False False  True]
[91 86 96]


In [48]:
# 두 조건문을 둘다 만족하는 경우는 & 연산자로 표현
# fix me! # 국어점수가 80점 이상, 95점 이하인 학생들의 국어점수

[False  True  True False False False]
[91 86]



#### 1) 국어 성적이 80점이 넘는 학생들의 성적을 가져오기

In [50]:
# fix me! # 국어 성적이 80점이 넘는 학생의 성적 데이터

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [96, 90, 95, 81, 72]])

#### 2) 수학 및 과학 성적 모두 80점이 넘는 학생들의 성적 가져오기

In [51]:
# fix me! # 모든 학생의 수학 성적 데이터
# fix me! # 모든 학생의 과학 성적 데이터
# fix me! # 각 학생의 수학과 과학 성적이 모두 80점이 넘는가? True / False 로 구성된 Boolean Mask

[False  True False False  True False]


In [52]:
# fix me! # 수학과 과학 성적이 모두 80점이 넘는 학생의 성적 데이터

array([[91, 75, 90, 68, 85],
       [75, 85, 85, 92, 95]])

## 3. `np.where`로 조건을 충족하는 값의 Index Array 만들어 가져오기

+ 비교 연산자를 `np.where()` 메소드에서 사용하면 조건을 충족하는 값의 인덱스로 구성된 Array를 반환합니다. 
+ Index Array로 인덱싱 하게 되면 앞서 리스트로 된 인덱싱 방법과 동일하게 작동합니다. 
+ `np.where()` 메소드는 조건에 해당하는 값을 원하는 값으로 바꾸는 기능도 제공합니다. 

### (1) `np.where`과 비교문으로 원하는 값 가져오기
np.array에서 **조건에 맞는 원소의 위치를 알고 싶으면 `np.where`를 이용**합니다. `np.where`는 조건의 결과가 True에 해당하는 값의 위치(인덱스 값)를 반환합니다. 앞서 인덱스를 설정하여 원하는 위치의 값만 특정하여 가져올 수 있다고 배웠습니다. 따라서 `.where()` 메소드로 반환받은 원소의 위치를 인덱스로 사용하면 조건에 맞는 원하는 값을 가져올 수 있습니다. 

#### 1) 국어 성적이 80점이 넘는 학생들의 성적을 가져오기

In [53]:
# fix me! # 모든 학생의 국어 성적 데이터
# fix me! # 국어성적이 80 점이 넘는 학생의 인덱스 

(array([1, 2, 5]),)

In [54]:
# fix me! # 국어 성적이 80점이 넘는 학생의 성적 데이터

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [96, 90, 95, 81, 72]])

#### 2) 수학 및 과학 성적 모두 80점이 넘는 학생들의 성적 가져오기

In [55]:
# fix me! # 모든 학생의 수학 성적 데이터
# fix me! # 모든 학생의 과학 성적 데이터
# fix me! # 수학 및 과학 성적 모두 80점이 넘는 학생들의 인덱스

(array([1, 4]),)

In [56]:
# fix me! # 수학 및 과학 성적 모두 80점이 넘는 학생들의 성적 가져오기

array([[91, 75, 90, 68, 85],
       [75, 85, 85, 92, 95]])

### (2) `np.where`과 비교문으로 조건에 맞는 값 수정하기

`np.where` 메소드는 조건에 따라 값을 치환할 수 있습니다. `np.where(condition, x, y)`로, 2번째 인자와 3번째 인자에 값이 입력되면, 조건에 맞는 경우 2번째 인자의 값으로, 조건에 안맞으면 3번째 인자의 값으로 대체됩니다.

In [57]:
# fix me! # 국어 성적이 80점이 넘으면 '합격', 80점 이하면 '불합격'

(array([1, 2, 5]),)
['불합격' '합격' '합격' '불합격' '불합격' '합격']


#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/08/25


---